# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-06 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20200205_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='listing',
            field=models.CharField(max_length=50),
        ),
    ]
