# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-22 12:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(default='', upload_to='media/%y/%m/%d')),
                ('description', models.TextField()),
                ('email', models.CharField(max_length=100)),
                ('phone_num', models.CharField(max_length=15)),
                ('is_mvp', models.BooleanField(default=True)),
                ('hire_date', models.DateField(default=datetime.datetime.today)),
            ],
        ),
    ]
